language: node_js
node_js:
- '0.10'
before_script:
- npm install grunt-cli -g
script:
- grunt
before_install:
- openssl aes-256-cbc -K $encrypted_b5c1912d5163_key -iv $encrypted_b5c1912d5163_iv
  -in travis-ssh-key.enc -out travis-ssh-key -d
