language: node_js
node_js:
- '0.10'

before_script:
- npm install grunt-cli -g
- mkdir $TRAVIS_BUILD_DIR/data

script:
- grunt
- mkdir $TRAVIS_BUILD_DIR/dist/data
- mkdir $TRAVIS_BUILD_DIR/dist/css/screen.css

before_install:
- if [[ $TRAVIS_PULL_REQUEST == "false" ]] ; then 
  openssl aes-256-cbc -K $encrypted_b5c1912d5163_key -iv $encrypted_b5c1912d5163_iv
  -in travis-ssh-key.enc -out travis-ssh-key -d ; fi

addons:
  ssh_known_hosts:
  - tools.adfc-hamburg.de

before_deploy:
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/travis-ssh-key
- ssh-add $TRAVIS_BUILD_DIR/travis-ssh-key
- chmod 750 $TRAVIS_BUILD_DIR/script/deploy.sh

deploy:
  provider: script
  skip_cleanup: true
  script: $TRAVIS_BUILD_DIR/script/deploy.sh
  on:
    all_branches: true

after_deploy:
- eval "$(ssh-agent -ks)"
