# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
# see also: https://github.com/filipesilva/ng-github-actions/blob/master/.github/workflows/main.yml
name: CI

on: [push]

jobs:
  build:

    # Machine environment:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm install
      run: npm install
    - name: Grunt
      run: grunt
    - name: Copy Screen.css and images
      run: |
        mkdir -p dist/css/images
        cp node_modules/leaflet/dist/images/* dist/css/images/
        cp apple-touch-icon.png favico* site.webmanifest android-chrome-*.png  dist/
        cp css/screen.css dist/css/
        cp css/roboto.css dist/css/
        cp -r fonts/roboto/ dist/fonts/
    - name: Get current time
      uses: srfrnk/current-time@master
      id: current-time
      with:
        format: YYYYMMDD-HHmmss
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: "adfc-t30-dist-${{ steps.current-time.outputs.formattedTime }}"
        path: dist/
    - name: Synchronize Git repository to Tools
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.SSH_T30_SECRET }}
        ARGS: "-e -c -r --delete"
        SERVER_PORT: 22
        FOLDER: "dist/"
        SERVER_IP: tools.adfc-hamburg.de
        USERNAME: github
        SERVER_DESTINATION: $GITHUB_REF
